/*
 COPYRIGHT 2012 ESRI
 
 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.
 
 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA
 
 email: contracts@esri.com
 */

/** @file AGSGPMessage.h */ //Required for Globals API doc

/** @brief A message generated by a geoprocessing task.
 
 Instances of this class represent messages generated during the execution of a 
 geoprocessing task. They include information such as when the task started, what 
 parameter values are being used, the progress of the task, warnings of 
 potential problems, and errors.
 
 @define{AGSGPMessage.h, ArcGIS}
 @agssince{1.0, 10.2}
 */
@interface AGSGPMessage : NSObject <AGSCoding>

/** The message type. Possible types include
 
 @li @c AGSGPMessageTypeInformative
 @li @c AGSGPMessageTypeProcessDefinition
 @li @c AGSGPMessageTypeStart
 @li @c AGSGPMessageTypeStop
 @li @c AGSGPMessageTypeWarning
 @li @c AGSGPMessageTypeError
 @li @c AGSGPMessageTypeEmpty
 @li @c AGSGPMessageTypeAbort
 
 @agssince{1.0, 10.2}
 */
@property (nonatomic, readonly) AGSGPMessageType type;

/** A description of the geoprocessing message.
 @agssince{1.0, 10.2}
 */
@property (nonatomic, copy, readonly) NSString *messageDescription;

@end