/*
 COPYRIGHT 2013 ESRI
 
 TRADE SECRETS: ESRI PROPRIETARY AND CONFIDENTIAL
 Unpublished material - all rights reserved under the
 Copyright Laws of the United States and applicable international
 laws, treaties, and conventions.
 
 For additional information, contact:
 Environmental Systems Research Institute, Inc.
 Attn: Contracts and Legal Services Department
 380 New York Street
 Redlands, California, 92373
 USA
 
 email: contracts@esri.com
 */

#import <Foundation/Foundation.h>

@protocol AGSCoding;

/** @file AGSGDBSyncTaskStatusInfo.h */ //Required for Globals API doc

/** @brief Status information operations related to geodatabase sync-enabled geodatabases
 
 This class holds information pertaining to operations such as downloading or syncing a sync-enabled geodatabase.
 
 @define{AGSGDBSyncTaskStatusInfo.h, ArcGIS}
 @agssince{10.2, 10.2}
 */
@interface AGSGDBSyncTaskStatusInfo : NSObject<AGSCoding>

/** The id of the job in which this status object corresponds to.
 @agssince{10.2, 10.2}
 */
@property (nonatomic, copy, readonly) NSString *jobID;

/** The date this geodatabase was last updated.
 @agssince{10.2, 10.2}
 */
@property (nonatomic, strong, readonly) NSDate *lastUpdatedTime;

/** This will report the unique geodatabase name generated by server.
 @agssince{10.2, 10.2}
 */
@property (nonatomic, copy, readonly) NSString *geodatabaseName;

/** The URL in which the results (changes or error information) from the server can be downloaded from.
 @agssince{10.2, 10.2}
 */
@property (nonatomic, strong, readonly) NSURL *resultURL;

/** The status of this particular job.
 @agssince{10.2, 10.2}
 */
@property (nonatomic, assign, readonly) AGSGDBSyncTaskJobStatus status;

/** The date in which this job was submitted to the server.
 @agssince{10.2, 10.2}
 */
@property (nonatomic, strong, readonly) NSDate *submissionTime;

@end
